# Generated by Django 5.0.4 on 2024-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
