# Generated by Django 5.0.4 on 2024-09-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
        ('patient', '0004_alter_patient_first_name_alter_patient_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
